# Generated by Django 4.2.10 on 2024-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_column='item_name', max_length=300)),
                ('item_description', models.TextField()),
            ],
        ),
    ]
